# Generated by Django 5.1.3 on 2024-12-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
