# Generated by Django 5.1.3 on 2024-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_ads_box_newsdata_ads_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='ads_Image',
            field=models.ImageField(blank=True, upload_to='ads_images/'),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='postImages',
            field=models.ImageField(blank=True, upload_to='news_images/'),
        ),
    ]
