# Generated by Django 5.1.3 on 2024-12-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_adsimage_images_remove_postimage_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='news',
        ),
        migrations.AddField(
            model_name='newsdata',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.postimage'),
        ),
        migrations.AlterField(
            model_name='adsimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images/'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
