# Generated by Django 5.1.3 on 2024-12-06 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_newsdata_image_postimage_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
