# Generated by Django 5.1.3 on 2024-12-08 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_newsdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='date_created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
