# Generated by Django 5.1.3 on 2024-12-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_newsdata_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
