# Generated by Django 5.1.3 on 2024-12-08 04:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_newsdata_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsdata',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterField(
            model_name='createadsimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
