# Generated by Django 5.1.3 on 2024-12-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_newsdata_options_alter_createadsimage_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsdata',
            options={},
        ),
    ]
