# Generated by Django 5.1.3 on 2024-12-08 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_newsdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createadsimage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
